// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TableEditorController from "./table_editor_controller"
application.register("table-editor", TableEditorController)

import TrixTableController from "./trix_table_controller"
application.register("trix-table", TrixTableController)
