// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"

// General Controllers
// -------------------
// import all Stimulus controller files under the controllers folder
import controllers from './**/*_controller.js'

// Auxiliary Methods
// -----------------
// Infer Stimulus controller name from its file
function controllerName(defaultName) {
    const namespaces = [
        ...new Set(
            defaultName
                .split('--')
                .filter((ns) => !['..', 'controllers'].includes(ns))
        )
    ]
    return namespaces.join('--')
}

const application = Application.start()

// Configure Stimulus development experience
application.debug = false
window.Stimulus = application


controllers.forEach((controller) => {
    Stimulus.register(controllerName(controller.name), controller.module.default)
})


// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

// import TableEditorController from "./table_editor_controller"
// application.register("table-editor", TableEditorController)

// import TrixTableController from "./trix_table_controller"
// application.register("trix-table", TrixTableController)
